### ISSUE TITLE
SP_Flat and SP_Toolbox error

### ISSUE THREAD

**Issue by Yeqzids** [Yeqzids/SP#3]
```
$> Library/SP/SP_Flat.py *FLAT* -b MasterBias.fits -o MasterFlat.fits -m index
Traceback (most recent call last):
  File "Library/SP/SP_Flat.py", line 125, in <module>
    Create_Flat(filenames,MasterName,Verbose,Bias,Series,Diagnostic)
  File "Library/SP/SP_Flat.py", line 73, in Create_Flat
    SP.Create_Flat(FileList,**FlatFlags)
  File "Library/SP/SP_Toolbox.py", line 832, in Create_Flat
    MasterFlat[MasterFlat == np.inf] = 1
TypeError: 'numpy.float64' object does not support item assignment
```

**Comment by Yeqzids** [comment]
This is because of wrong `-m` setting -- the dataset I used should have `-m none`, but I mistakenly set it to `-m index`. Correct setting will not produce this error.
