### ISSUE TITLE
SP_WavCal.py: error loading pickle object

### ISSUE THREAD

**Issue by Yeqzids** [Yeqzids/SP#9]
https://github.com/Yeqzids/SP/blob/11e286adebe3b50b5056159423191fe1644e8f92/SP_WavCal.py#L84

```
Traceback (most recent call last):
  File "/SP/SP_WavCal.py", line 179, in <module>
    WavCal(filenames,ArcsFile,OutFile,Verbose,Method)
  File "/SP/SP_WavCal.py", line 84, in WavCal
    Pre = pickle.load(f)
TypeError: a bytes-like object is required, not 'str'
```

If I change the previous line from 'r' to 'rb', then

```
Traceback (most recent call last):
  File "/SP/SP_WavCal.py", line 179, in <module>
    WavCal(filenames,ArcsFile,OutFile,Verbose,Method)
  File "/SP/SP_WavCal.py", line 84, in WavCal
    Pre = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa8 in position 1: ordinal not in range(128)
```

**Comment by Yeqzids** [comment]
Fixed in 2f331c7.
